image: node:latest
cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  before_script:
    - apt-get update -y && apt-get install curl -y
    - curl -o- -L https://yarnpkg.com/install.sh | bash
  script:
    - yarn install --prod
    - yarn run build
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
